apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hpa-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: php.sainath.quest
    http:
      paths:
      - backend:
          service:
            name: php-apache
            port:
              number: 80
        path: /
        pathType: Prefix
